# methods in dictionary: len(), pop(), popitem(), del(), clear(), dict(), values(), items(), get()
dic = dict()
print(dic)
print('\n')
dic = ('studid':1001, 'studid':'Rohit','Branch':'Cse')
print(dic)
print(dic.keys())
print(dic.values())
print(dic.items())